CursedPathWebApp/Models/ModalFooter.cs
namespace CursedPathWebApp.Models
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Submit";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

CursedPathWebApp/Models/ModalHeader.cs
namespace CursedPathWebApp.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

CursedPathWebApp/Models/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursedPathWebApp.Data;

namespace CursedPathWebApp.Models
{
    public class ScheduleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ScheduleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Schedule
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Schedule.Include(s => s.VenueModel);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Schedule/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleListViewModel = await _context.Schedule
                .Include(s => s.VenueModel)
                .SingleOrDefaultAsync(m => m.ShowId == id);
            if (scheduleListViewModel == null)
            {
                return NotFound();
            }

            return View(scheduleListViewModel);
        }

        // GET: Schedule/Create
        public IActionResult Create()
        {
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "Location");
            return View();
        }

        // POST: Schedule/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShowId,Date,Time,VenueId")] ScheduleListViewModel scheduleListViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scheduleListViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "Location", scheduleListViewModel.VenueId);
            return View(scheduleListViewModel);
        }

        // GET: Schedule/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleListViewModel = await _context.Schedule.SingleOrDefaultAsync(m => m.ShowId == id);
            if (scheduleListViewModel == null)
            {
                return NotFound();
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "Location", scheduleListViewModel.VenueId);
            return View(scheduleListViewModel);
        }

        // POST: Schedule/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShowId,Date,Time,VenueId")] ScheduleListViewModel scheduleListViewModel)
        {
            if (id != scheduleListViewModel.ShowId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scheduleListViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleListViewModelExists(scheduleListViewModel.ShowId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "Location", scheduleListViewModel.VenueId);
            return View(scheduleListViewModel);
        }

        // GET: Schedule/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleListViewModel = await _context.Schedule
                .Include(s => s.VenueModel)
                .SingleOrDefaultAsync(m => m.ShowId == id);
            if (scheduleListViewModel == null)
            {
                return NotFound();
            }

            return View(scheduleListViewModel);
        }

        // POST: Schedule/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var scheduleListViewModel = await _context.Schedule.SingleOrDefaultAsync(m => m.ShowId == id);
            _context.Schedule.Remove(scheduleListViewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleListViewModelExists(int id)
        {
            return _context.Schedule.Any(e => e.ShowId == id);
        }
    }
}

CursedPathWebApp/Controllers/BandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CursedPathWebApp.Controllers
{
    public class BandController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Chat()
        {
            return View();
        }
    }
}

CursedPathWebApp/Views/Shared/_BandLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using CursedPathWebApp.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (User.IsInRole("Admin") || User.IsInRole("Band Member"))
{
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a asp-area="" asp-controller="Schedule" asp-action="Index">Schedule</a>
        <a asp-area="" asp-controller="Band" asp-action="Chat">Message Board</a>
        <a asp-area="" asp-controller="Setlist" asp-action="Index">Setlist</a>
    </div>
    <button class="glyphButton" id="openButt" onclick="openNav()"><i class="glyphicon glyphicon-menu-hamburger"></i></button>
    
}

@if (User.IsInRole("Admin"))
{
    <ul class="nav navbar-nav navbar-left">
        <li><a asp-area="" asp-controller="ApplicationRole" asp-action="Index">
            <i class="glyphicon glyphicon-edit"></i>
            <b>ADMIN PAGE</b>
            </a>
        </li>
    </ul>
}

CursedPathWebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims 
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cursed Path</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Covered+By+Your+Grace" rel="stylesheet"> 
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/rowreorder/1.2.3/js/dataTables.rowReorder.min.js"></script>
</head>

<body style="position: relative; background-color: rgb(28, 26, 26); padding-top: 0px;">
    <div id="main"style="margin-left: 0px; padding-right: 0px; padding-left: 0px; padding-top: 0px;">
        <nav class="navbar navbar-inverse navbar-fixed-top" id="myNav">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                        <img src="~/images/CursedPath.jpg" class="img-responsive" alt="Cursed Path" height="76" width="100">
                    </a>
                </div>

                <div class="navbar-collapse collapse">
                    @await Html.PartialAsync("_LoginPartial")
                    <ul class="nav navbar-nav navbar-right">

                        <li><a asp-area="" asp-controller="Home" asp-action="Index">HoME</a></li>

                    </ul>

                    @await Html.PartialAsync("_BandLoginPartial")
                </div>
            </div>
        </nav>
        <div id="sidebar">
            <div id="slideout">
                <iframe style="border: 0; width: 350px; height: 588px;" src="https://bandcamp.com/EmbeddedPlayer/album=3478440568/size=large/bgcol=333333/linkcol=e32c14/transparent=true/" seamless><a href="http://cursedpath.bandcamp.com/album/demo-2016">DEMO 2016 by Cursed Path</a></iframe>
            </div>
            <button type="submit" id="pullBtn" style="border: 0; background: transparent">
                <img src="~/images/PullOut.png" width="74" height="100">
                <img />
            </button>
        </div>


        <div class="container body-content">

            @RenderBody()
            <hr />
            <footer>
                <p class="pcenter">&copy; 2017 - CursedPathWebApp</p>
                <p class="pcenter">Cursed Path is a Hardcore band from Pomeroy, Ohio</p>
                <p class="pcenter">Thanks for checking us out!</p>
                <p class="pcenter">
                    <row>
                        <a href="https://www.facebook.com/cursedpath/"><span class="fa fa-facebook-square" style="font-size:24px"></span></a>
                        <a href="https://twitter.com/cursedpathhc"><span class="fa fa-twitter" style="font-size:24px"></span></a>
                        <a href="https://www.instagram.com/cursedpathhc/"><span class="fa fa-instagram" style="font-size:24px"></span></a>
                    </row>
                </p>
                <br />
                <br />
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/js/nav.js" asp-append-version="true"></script>
            <script src="~/js/board.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>

        </environment>


        @RenderSection("Scripts", required: false)
    </div>

</body>
</html>

CursedPathWebApp/Views/Shared/_Modal.cshtml
@model CursedPathWebApp.Models.BootstrapModel

<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div>

CursedPathWebApp/Views/Shared/_ModalFooter.cshtml
@model CursedPathWebApp.Models.ModalFooter

<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">
            @Model.SubmitButtonText
        </button>
    }
</div> 

CursedPathWebApp/Views/Shared/_ModalHeader.cshtml
@model CursedPathWebApp.Models.ModalHeader

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>