CursedPathWebApp/Controllers/HeadlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using CursedPathWebApp.Data;
using CursedPathWebApp.Models;

namespace CursedPathWebApp.Controllers
{
    [Authorize(Roles="Admin,Band Member")]
    public class HeadlineController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public HeadlineController(UserManager<ApplicationUser> userManager, ApplicationDbContext ctx)
        {
            _userManager = userManager;
            _context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(string title, string contentHTML)
        {
            var post = new BlogPost
            {
                Author = await _userManager.GetUserAsync(HttpContext.User),
                Title = title,
                DatePosted = DateTime.Now,
                ContentHTML = contentHTML
            };

            await _context.BlogPosts.AddAsync(post);
            await _context.SaveChangesAsync();

            return RedirectToAction("Manage");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            var post = await _context.FindAsync<BlogPost>(id);
            if (post.Author == user)
            {
                post.Deleted = true;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Manage");
        }

        [HttpGet]
        public async Task<IActionResult> Manage()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            ViewBag.userId = user.Id;
            return View(_context.BlogPosts.Where(post => !post.Deleted).OrderByDescending(post => post.DatePosted).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            var post = await _context.FindAsync<BlogPost>(id);
            if (post.Author == user)
            {
                return View(post);
            }
            return RedirectToAction("Manage");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, string title, string contentHTML)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            var post = await _context.FindAsync<BlogPost>(id);
            if (post.Author == user)
            {
                post.Title = title;
                post.ContentHTML = contentHTML;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Manage");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Archive()
        {
            return View(_context.BlogPosts.Where(post => !post.Deleted).OrderByDescending(post => post.DatePosted).ToList());
        }
    }
}

CursedPathWebApp/Controllers/ManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CursedPathWebApp.Models;
using CursedPathWebApp.Models.ManageViewModels;
using CursedPathWebApp.Services;

namespace CursedPathWebApp.Controllers
{
    [Authorize]
    public class ManageController : Controller
    {
        private readonly UserManager<Data.ApplicationUser> _userManager;
        private readonly SignInManager<Data.ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;

        public ManageController(
        UserManager<Data.ApplicationUser> userManager,
        SignInManager<Data.ApplicationUser> signInManager,
        IEmailSender emailSender,
        ISmsSender smsSender,
        ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<ManageController>();
        }

        //
        // GET: /Manage/Index
        [HttpGet]
        public async Task<IActionResult> Index(ManageMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }
            var model = new IndexViewModel
            {
                HasPassword = await _userManager.HasPasswordAsync(user),
                PhoneNumber = await _userManager.GetPhoneNumberAsync(user),
                TwoFactor = await _userManager.GetTwoFactorEnabledAsync(user),
                Logins = await _userManager.GetLoginsAsync(user),
                BrowserRemembered = await _signInManager.IsTwoFactorClientRememberedAsync(user)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveLogin(RemoveLoginViewModel account)
        {
            ManageMessageId? message = ManageMessageId.Error;
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.RemoveLoginAsync(user, account.LoginProvider, account.ProviderKey);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    message = ManageMessageId.RemoveLoginSuccess;
                }
            }
            return RedirectToAction(nameof(ManageLogins), new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public IActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }
            var code = await _userManager.GenerateChangePhoneNumberTokenAsync(user, model.PhoneNumber);
            await _smsSender.SendSmsAsync(model.PhoneNumber, "Your security code is: " + code);
            return RedirectToAction(nameof(VerifyPhoneNumber), new { PhoneNumber = model.PhoneNumber });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnableTwoFactorAuthentication()
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                await _userManager.SetTwoFactorEnabledAsync(user, true);
                await _signInManager.SignInAsync(user, isPersistent: false);
                _logger.LogInformation(1, "User enabled two-factor authentication.");
            }
            return RedirectToAction(nameof(Index), "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisableTwoFactorAuthentication()
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                await _userManager.SetTwoFactorEnabledAsync(user, false);
                await _signInManager.SignInAsync(user, isPersistent: false);
                _logger.LogInformation(2, "User disabled two-factor authentication.");
            }
            return RedirectToAction(nameof(Index), "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        [HttpGet]
        public async Task<IActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }
            var code = await _userManager.GenerateChangePhoneNumberTokenAsync(user, phoneNumber);
            // Send an SMS to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.ChangePhoneNumberAsync(user, model.PhoneNumber, model.Code);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction(nameof(Index), new { Message = ManageMessageId.AddPhoneSuccess });
                }
            }
            // If we got this far, something failed, redisplay the form
            ModelState.AddModelError(string.Empty, "Failed to verify phone number");
            return View(model);
        }

        //
        // POST: /Manage/RemovePhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemovePhoneNumber()
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.SetPhoneNumberAsync(user, null);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction(nameof(Index), new { Message = ManageMessageId.RemovePhoneSuccess });
                }
            }
            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.Error });
        }

        //
        // GET: /Manage/ChangePassword
        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation(3, "User changed their password successfully.");
                    return RedirectToAction(nameof(Index), new { Message = ManageMessageId.ChangePasswordSuccess });
                }
                AddErrors(result);
                return View(model);
            }
            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.Error });
        }

        //
        // GET: /Manage/SetPassword
        [HttpGet]
        public IActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.AddPasswordAsync(user, model.NewPassword);
                if (result.Succeeded)
                {

CursedPathWebApp/Views/Headline/Add.cshtml
@{
    ViewBag.Title = "Add Headline";
}

<h2>Manage</h2>
<link href="https://cdn.quilljs.com/1.3.4/quill.snow.css" rel="stylesheet">

<div class="panel panel-primary" style="padding: 2ex">
@using (Html.BeginForm("Add", "Headline")) {
    @Html.Hidden("contentHTML", "", new { id = "hiddenHTML" })
    <div class="input-group">
        @Html.Label("title", "Title")
        @Html.TextBox("title", "", null, new { @class = "form-control" })
    </div>
    <div>&nbsp;</div>
    <div id="richtext">
    </div>
    <div>&nbsp;</div>
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add</button>
}
<script type="text/javascript" src="https://cdn.quilljs.com/1.3.4/quill.js"></script>
<script type="text/javascript">
    var quill = new Quill('#richtext', {
        modules: {
            toolbar: [
                ['bold', 'italic', 'underline', 'strike'],
                ['link'],
                [{ 'size': ['small', 'normal', 'large'] }]
            ]
        },
        theme: 'snow'
    });
    quill.on('text-change', function (delta, oldDelta, source) {
        var html = quill.container.querySelector('.ql-editor').innerHTML;
        $('#hiddenHTML').val(html);
    });
</script>
</div>

CursedPathWebApp/Views/Headline/Archive.cshtml
@model IEnumerable<CursedPathWebApp.Models.BlogPost>
@using CursedPathWebApp.Models
@{
    ViewBag.Title = "Headline Archive";
}

<h2>@ViewBag.Title</h2>

<div class="container" id="archive-container">
    @foreach (BlogPost post in Model)
    {
        <div class="row">
            <h3 class="archive-post-title">@post.Title</h3>
            <div class="archive-post-date">@post.DatePosted</div>
            <div class="archive-post-content">
                @Html.Raw(post.ContentHTML)
            </div>
        </div>
    }
</div>

CursedPathWebApp/Views/Headline/Edit.cshtml
@model CursedPathWebApp.Models.BlogPost
@{
    ViewBag.Title = "Edit";
}
<h2>Manage</h2>
<link href="https://cdn.quilljs.com/1.3.4/quill.snow.css" rel="stylesheet">

<div class="panel panel-primary" style="padding: 2ex">
@using (Html.BeginForm("Edit", "Headline"))
{
    @Html.Hidden("id", Model.Id)
    @Html.Hidden("contentHTML", Model.ContentHTML, new { id = "hiddenHTML" })
    <div class="input-group">
        @Html.Label("title", "Title")
        @Html.TextBox("title", Model.Title, null, new { @class = "form-control" })
    </div>
    <div>&nbsp;</div>
    <div id="richtext">
        @Html.Raw(Model.ContentHTML)
    </div>
    <div>&nbsp;</div>
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save Changes</button>
}
<script type="text/javascript" src="https://cdn.quilljs.com/1.3.4/quill.js"></script>
<script type="text/javascript">
    var quill = new Quill('#richtext', {
        modules: {
            toolbar: [
                ['bold', 'italic', 'underline', 'strike'],
                ['link'],
                [ { 'size': ['small', 'normal', 'large'] } ]
            ]
        },
        theme: 'snow'
    });
    quill.on('text-change', function (delta, oldDelta, source) {
        var html = quill.container.querySelector('.ql-editor').innerHTML;
        $('#hiddenHTML').val(html);
    });
</script>
</div>

CursedPathWebApp/Views/Headline/Manage.cshtml
@model IEnumerable<CursedPathWebApp.Models.BlogPost>
@using CursedPathWebApp.Models
@{
    ViewBag.Title = "Manage Headlines";
}

<h2>@ViewBag.Title</h2>

<div class="panel panel-primary">
    <div class="panel-body">
        <div class="btn-group">
            @Html.ActionLink("Add", "Add", new { }, new { @class = "btn btn-primary" })
        </div>

        <table class="table table-bordered table-striped">
            @foreach (BlogPost post in Model)
            {
                <tr>
                    <td>
                        @post.Title
                    </td>
                    <td>
                        @post.DatePosted
                    </td>
                    <td>
                        @if (User.IsInRole("Admin") || post.Author.Id == ViewBag.userId)
                        {
                            <div class="btn-group">
                                @Html.ActionLink("Edit", "Edit", new { id = post.Id }, new { @class = "btn btn-secondary" })
                                @Html.ActionLink("Delete", "Delete", new { id = post.Id }, new { @class = "btn btn-danger" })
                            </div>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>